#----------------------------------------------------------------------------
#  Copyright (c) 2018 WSO2, Inc. http://www.wso2.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#----------------------------------------------------------------------------
---
- name: Set rpm_setup_path
  set_fact:
    setup_path: "{{ rpm_setup_path }}"
    java_home: '"{{ rpm_setup_path }}/{{ product_name }}/{{ product_version }}/jdk/{{ java_version }}"'
  when: ansible_os_family == "RedHat"

- name: Set deb_setup_path
  set_fact:
    setup_path: "{{ deb_setup_path }}"
    java_home: '"{{ deb_setup_path }}/{{ product_name }}/{{ product_version }}/jdk/{{ java_version }}"'
  when: ansible_os_family == "Debian"

- block:
    - name: Copy the Debian package of WSO2 API Manager Analytics
      copy:
        src: "{{ product_package_location }}/{{ product_archive_deb }}"
        dest: "{{ product_path }}/{{product_archive_deb }}"
        mode: 0755
      when: ansible_os_family == "Debian"

    - name: Copy the RPM package of WSO2 API Manager Analytics
      copy:
        src: "{{ product_package_location }}/{{ product_archive_rpm  }}"
        dest: "{{ product_path  }}/{{ product_archive_rpm  }}"
        mode: 0755
      when: ansible_os_family == "RedHat"

    - name: Install analytics .deb package
      apt:
        deb: "/opt/wso2/{{ product_archive_deb  }}"
      when: ansible_os_family == "Debian"

    - name: Install a .rpm package
      yum:
        name: "{{ product_path  }}/{{ product_archive_rpm  }}"
      when: ansible_os_family == "RedHat"

    - name: "Copy JDBC Driver"
      copy:
        src: "files/{{ jdbc_driver }}"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/lib"

    - name: "Copy deployment.yaml"
      template:
        src: "carbon-home/conf/worker/deployment.yaml.j2"
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/conf/worker/deployment.yaml"

    - name: Copy carbon.sh
      template:
        src: carbon-home/wso2/worker/bin/carbon.sh.j2
        dest: "{{ setup_path }}/{{ product_name }}/{{ product_version }}/wso2/worker/bin/carbon.sh"

    # Enable customization by uncommenting the following and adding the changes to the custom.yml
    # - import_tasks: custom.yml

    - name: Change the owner of WSO2 directory
      file:
        path: "{{ setup_path }}"
        state: directory
        recurse: true
        owner: "{{ wso2_user }}"
        group: "{{ wso2_group }}"
        mode: 0755

  when: "(inventory_hostname in groups['apim-analytics-worker'])"
  become: true
  become_user: root

- block:
    #- name: Add mappings to /etc/hosts
    #  blockinfile:
    #    path: /etc/hosts
    #    block: |
    #      {{ item.ip }} {{ item.name }}
    #    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    #  with_items:
    #    - { name: apim-analytics-worker-1, ip: 10.0.15.11 }
    #    - { name: apim-analytics-worker-2, ip: 10.0.15.12 }

    - name: "Remove the first entry from the /etc/hosts"
      script: scripts/script.sh

    - name: "Copy WSO2AM Analytics worker service file"
      template:
        src: "wso2am-analytics-worker.service.j2"
        dest: /etc/systemd/system/wso2am-analytics-worker.service

    - name: "Reload systemctl daemon"
      command: systemctl daemon-reload

    - name: "Start wso2am-analytics-worker as a service"
      command: systemctl start wso2am-analytics-worker.service




  become: true
  become_user: root
